/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdUpdatesRouteImport } from './routes/$projectId.updates'
import { Route as ProjectIdDocsRouteImport } from './routes/$projectId.docs'
import { Route as ProjectIdUpdatesSlugRouteImport } from './routes/$projectId.updates.$slug'
import { Route as ProjectIdDocsSlugRouteImport } from './routes/$projectId.docs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdUpdatesRoute = ProjectIdUpdatesRouteImport.update({
  id: '/$projectId/updates',
  path: '/$projectId/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdDocsRoute = ProjectIdDocsRouteImport.update({
  id: '/$projectId/docs',
  path: '/$projectId/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdUpdatesSlugRoute = ProjectIdUpdatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectIdUpdatesRoute,
} as any)
const ProjectIdDocsSlugRoute = ProjectIdDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectIdDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId/docs': typeof ProjectIdDocsRouteWithChildren
  '/$projectId/updates': typeof ProjectIdUpdatesRouteWithChildren
  '/$projectId/docs/$slug': typeof ProjectIdDocsSlugRoute
  '/$projectId/updates/$slug': typeof ProjectIdUpdatesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectId/docs': typeof ProjectIdDocsRouteWithChildren
  '/$projectId/updates': typeof ProjectIdUpdatesRouteWithChildren
  '/$projectId/docs/$slug': typeof ProjectIdDocsSlugRoute
  '/$projectId/updates/$slug': typeof ProjectIdUpdatesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId/docs': typeof ProjectIdDocsRouteWithChildren
  '/$projectId/updates': typeof ProjectIdUpdatesRouteWithChildren
  '/$projectId/docs/$slug': typeof ProjectIdDocsSlugRoute
  '/$projectId/updates/$slug': typeof ProjectIdUpdatesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId/docs'
    | '/$projectId/updates'
    | '/$projectId/docs/$slug'
    | '/$projectId/updates/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$projectId/docs'
    | '/$projectId/updates'
    | '/$projectId/docs/$slug'
    | '/$projectId/updates/$slug'
  id:
    | '__root__'
    | '/'
    | '/$projectId/docs'
    | '/$projectId/updates'
    | '/$projectId/docs/$slug'
    | '/$projectId/updates/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdDocsRoute: typeof ProjectIdDocsRouteWithChildren
  ProjectIdUpdatesRoute: typeof ProjectIdUpdatesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/updates': {
      id: '/$projectId/updates'
      path: '/$projectId/updates'
      fullPath: '/$projectId/updates'
      preLoaderRoute: typeof ProjectIdUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/docs': {
      id: '/$projectId/docs'
      path: '/$projectId/docs'
      fullPath: '/$projectId/docs'
      preLoaderRoute: typeof ProjectIdDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/updates/$slug': {
      id: '/$projectId/updates/$slug'
      path: '/$slug'
      fullPath: '/$projectId/updates/$slug'
      preLoaderRoute: typeof ProjectIdUpdatesSlugRouteImport
      parentRoute: typeof ProjectIdUpdatesRoute
    }
    '/$projectId/docs/$slug': {
      id: '/$projectId/docs/$slug'
      path: '/$slug'
      fullPath: '/$projectId/docs/$slug'
      preLoaderRoute: typeof ProjectIdDocsSlugRouteImport
      parentRoute: typeof ProjectIdDocsRoute
    }
  }
}

interface ProjectIdDocsRouteChildren {
  ProjectIdDocsSlugRoute: typeof ProjectIdDocsSlugRoute
}

const ProjectIdDocsRouteChildren: ProjectIdDocsRouteChildren = {
  ProjectIdDocsSlugRoute: ProjectIdDocsSlugRoute,
}

const ProjectIdDocsRouteWithChildren = ProjectIdDocsRoute._addFileChildren(
  ProjectIdDocsRouteChildren,
)

interface ProjectIdUpdatesRouteChildren {
  ProjectIdUpdatesSlugRoute: typeof ProjectIdUpdatesSlugRoute
}

const ProjectIdUpdatesRouteChildren: ProjectIdUpdatesRouteChildren = {
  ProjectIdUpdatesSlugRoute: ProjectIdUpdatesSlugRoute,
}

const ProjectIdUpdatesRouteWithChildren =
  ProjectIdUpdatesRoute._addFileChildren(ProjectIdUpdatesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdDocsRoute: ProjectIdDocsRouteWithChildren,
  ProjectIdUpdatesRoute: ProjectIdUpdatesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
